namespace SpriteKind {
    export const COIN = SpriteKind.create()
    export const teleporter = SpriteKind.create()
    export const grav = SpriteKind.create()
}
function level4 () {
    tiles.setCurrentTilemap(tilemap`level10`)
    tiles.placeOnRandomTile(dryad, assets.tile`myTile2`)
    newlevel()
    scene.setBackgroundColor(2)
    g = 1
}
function level1 () {
    info.setLife(3)
    scene.setBackgroundColor(9)
    scene.cameraFollowSprite(dryad)
    tiles.setCurrentTilemap(tilemap`level5`)
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (dryad.isHittingTile(CollisionDirection.Left) || dryad.isHittingTile(CollisionDirection.Right) || dryad.isHittingTile(CollisionDirection.Bottom)) {
        dryad.vy = m
    }
    if (g == -1) {
        if (dryad.isHittingTile(CollisionDirection.Left) || dryad.isHittingTile(CollisionDirection.Right) || dryad.isHittingTile(CollisionDirection.Top)) {
            dryad.vy = m * g
        }
    }
})
function level5 () {
    tiles.setCurrentTilemap(tilemap`level10`)
    tiles.placeOnRandomTile(dryad, assets.tile`myTile2`)
    newlevel()
    scene.setBackgroundColor(15)
    g = 1
}
function level3 () {
    tiles.setCurrentTilemap(tilemap`level10`)
    tiles.placeOnRandomTile(dryad, assets.tile`myTile2`)
    newlevel()
    scene.setBackgroundColor(3)
    g = 1
}
function die () {
    if (info.life() > 1) {
        if (level == 1) {
            level1()
        } else if (level == 2) {
            level2()
        } else if (level == 3) {
            level3()
        } else if (level == 4) {
            level4()
        } else {
            level5()
        }
        info.changeLifeBy(-1)
    } else {
        game.gameOver(false)
    }
}
info.onCountdownEnd(function () {
    die()
})
function level2 () {
    tiles.setCurrentTilemap(tilemap`level9`)
    tiles.placeOnRandomTile(dryad, assets.tile`myTile2`)
    newlevel()
    scene.setBackgroundColor(5)
    dryad.ay = 350
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.grav, function (sprite, otherSprite) {
    if (g == -1) {
        g = 1
    } else if (g == 1) {
        g = -1
    }
    pauseUntil(() => false)
})
function newlevel () {
    controller.moveSprite(dryad, 150, 0)
    m = -150
    info.startCountdown(90)
    coinseaten = 0
    for (let value of tiles.getTilesByType(sprites.dungeon.collectibleInsignia)) {
        coin = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . f 5 5 5 5 5 5 5 5 f . . . 
            . . f 5 5 5 1 5 5 1 5 5 5 f . . 
            . . f 5 5 5 1 5 1 5 5 5 5 f . . 
            . . f 5 5 5 1 1 5 5 5 5 5 f . . 
            . . f 5 5 5 1 1 5 5 5 5 5 f . . 
            . . f 5 5 5 1 5 1 5 5 5 5 f . . 
            . . f 5 5 5 1 5 5 1 5 5 5 f . . 
            . . f 5 5 5 1 5 5 1 5 5 5 f . . 
            . . . f 5 5 5 5 5 5 5 5 f . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.COIN)
        animation.runImageAnimation(
        coin,
        [img`
            . . . . . . . . . . . . . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . f 5 5 5 5 5 5 5 5 f . . . 
            . . f 5 5 5 1 5 5 1 5 5 5 f . . 
            . . f 5 5 5 1 5 1 5 5 5 5 f . . 
            . . f 5 5 5 1 1 5 5 5 5 5 f . . 
            . . f 5 5 5 1 1 5 5 5 5 5 f . . 
            . . f 5 5 5 1 5 1 5 5 5 5 f . . 
            . . f 5 5 5 1 5 5 1 5 5 5 f . . 
            . . f 5 5 5 1 5 5 1 5 5 5 f . . 
            . . . f 5 5 5 5 5 5 5 5 f . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . f 5 5 5 1 1 5 5 5 f . . . 
            . . . f 5 5 5 1 5 5 5 5 f . . . 
            . . . f 5 5 5 1 5 5 5 5 f . . . 
            . . . f 5 5 5 1 5 5 5 5 f . . . 
            . . . f 5 5 5 1 5 5 5 5 f . . . 
            . . . f 5 5 5 1 1 5 5 5 f . . . 
            . . . f 5 5 5 1 1 5 5 5 f . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . f f . . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . . f f . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . f f . . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . . f f . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . f f . . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . . f f . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . f . . . . . . . 
            . . . . . . . f 5 f . . . . . . 
            . . . . . . . f 5 f . . . . . . 
            . . . . . . . f 5 f . . . . . . 
            . . . . . . . f 5 f . . . . . . 
            . . . . . . . f 5 f . . . . . . 
            . . . . . . . f 5 f . . . . . . 
            . . . . . . . f 5 f . . . . . . 
            . . . . . . . . f . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . f f . . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . . f f . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . f f . . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . . f f . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . f f . . . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . . f 5 5 f . . . . . . 
            . . . . . . . f f . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . f 5 5 5 1 1 5 5 5 f . . . 
            . . . f 5 5 5 1 5 5 5 5 f . . . 
            . . . f 5 5 5 1 5 5 5 5 f . . . 
            . . . f 5 5 5 1 5 5 5 5 f . . . 
            . . . f 5 5 5 1 5 5 5 5 f . . . 
            . . . f 5 5 5 1 1 5 5 5 f . . . 
            . . . f 5 5 5 1 1 5 5 5 f . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . . f 5 5 5 5 f . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . f 5 5 5 5 5 5 5 5 f . . . 
            . . f 5 5 5 1 5 5 1 5 5 5 f . . 
            . . f 5 5 5 1 5 1 5 5 5 5 f . . 
            . . f 5 5 5 1 1 5 5 5 5 5 f . . 
            . . f 5 5 5 1 1 5 5 5 5 5 f . . 
            . . f 5 5 5 1 5 1 5 5 5 5 f . . 
            . . f 5 5 5 1 5 5 1 5 5 5 f . . 
            . . f 5 5 5 1 5 5 1 5 5 5 f . . 
            . . . f 5 5 5 5 5 5 5 5 f . . . 
            . . . . f 5 5 5 5 5 5 f . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `],
        100,
        true
        )
        tiles.placeOnTile(coin, value)
        tiles.setTileAt(value, assets.tile`transparency16`)
    }
    for (let value of tiles.getTilesByType(sprites.dungeon.collectibleBlueCrystal)) {
        tele2 = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . 6 6 6 6 . . . . . . 
            . . . . 6 6 6 5 5 6 6 6 . . . . 
            . . . 7 7 7 7 6 6 6 6 6 6 . . . 
            . . 6 7 7 7 7 8 8 8 1 1 6 6 . . 
            . . 7 7 7 7 7 8 8 8 1 1 5 6 . . 
            . 6 7 7 7 7 8 8 8 8 8 5 5 6 6 . 
            . 6 7 7 7 8 8 8 6 6 6 6 5 6 6 . 
            . 6 6 7 7 8 8 6 6 6 6 6 6 6 6 . 
            . 6 8 7 7 8 8 6 6 6 6 6 6 6 6 . 
            . . 6 8 7 7 8 6 6 6 6 6 8 6 . . 
            . . 6 8 8 7 8 8 6 6 6 8 6 6 . . 
            . . . 6 8 8 8 8 8 8 8 8 6 . . . 
            . . . . 6 6 8 8 8 8 6 6 . . . . 
            . . . . . . 6 6 6 6 . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.teleporter)
        tiles.placeOnTile(tele2, value)
        tiles.setTileAt(value, assets.tile`transparency16`)
    }
    for (let value of tiles.getTilesByType(sprites.dungeon.collectibleRedCrystal)) {
        gchange = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . 4 4 4 4 . . . . . . 
            . . . . 4 4 4 5 5 4 4 4 . . . . 
            . . . 3 3 3 3 4 4 4 4 4 4 . . . 
            . . 4 3 3 3 3 2 2 2 1 1 4 4 . . 
            . . 3 3 3 3 3 2 2 2 1 1 5 4 . . 
            . 4 3 3 3 3 2 2 2 2 2 5 5 4 4 . 
            . 4 3 3 3 2 2 2 4 4 4 4 5 4 4 . 
            . 4 4 3 3 2 2 4 4 4 4 4 4 4 4 . 
            . 4 2 3 3 2 2 4 4 4 4 4 4 4 4 . 
            . . 4 2 3 3 2 4 4 4 4 4 2 4 . . 
            . . 4 2 2 3 2 2 4 4 4 2 4 4 . . 
            . . . 4 2 2 2 2 2 2 2 2 4 . . . 
            . . . . 4 4 2 2 2 2 4 4 . . . . 
            . . . . . . 4 4 4 4 . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.grav)
        tiles.placeOnTile(gchange, value)
        tiles.setTileAt(value, assets.tile`transparency16`)
    }
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.teleporter, function (sprite, otherSprite) {
    for (let value of tiles.getTilesByType(assets.tile`myTile4`)) {
        tiles.placeOnTile(dryad, value)
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.COIN, function (sprite, otherSprite) {
    coinseaten += 1
    sprites.destroy(otherSprite)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairLarge, function (sprite, location) {
    if (level == 1) {
        level2()
        level += 1
    } else if (level == 2) {
        level3()
        level += 1
    } else if (level == 3) {
        level4()
        level += 1
    } else if (level == 4) {
        level5()
        level += 1
    } else {
        game.gameOver(true)
    }
})
let gchange: Sprite = null
let tele2: Sprite = null
let coin: Sprite = null
let coinseaten = 0
let g = 0
let level = 0
let m = 0
let dryad: Sprite = null
dryad = sprites.create(img`
    ..............................
    ..............................
    ...............f..............
    ..............fef.............
    .............fecef............
    ............fecfcef...........
    ...........fecf5fcef..........
    ..........fecf525fcef.........
    ...........fecf5fcef..........
    ............fecfcef...........
    .............fecef............
    ..............fef.............
    ............eeeeeee...........
    ...........ee.eee.ee..........
    ...........ee.eee.ee..........
    ...........ee.eee.ee..........
    ...........ee.eee.ee..........
    ...........ee.eee.ee..........
    ..............eee.............
    .............eeeee............
    ............eee.e.e...........
    ............e.e.e..e..........
    ...........eee.eeee.e.........
    ...........e.e.e..ee..........
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    `, SpriteKind.Player)
m = -150
level = 1
g = 1
dryad.ay = 350 * g
controller.moveSprite(dryad, 100, 0)
level1()
game.onUpdate(function () {
    dryad.setImage(img`
        ..............................
        ..............................
        ...............f..............
        ..............fef.............
        .............fecef............
        ............fecfcef...........
        ...........fecf5fcef..........
        ..........fecf525fcef.........
        ...........fecf5fcef..........
        ............fecfcef...........
        .............fecef............
        ..............fef.............
        ............eeeeeee...........
        ...........ee.eee.ee..........
        ...........ee.eee.ee..........
        ...........ee.eee.ee..........
        ...........ee.eee.ee..........
        ...........ee.eee.ee..........
        ..............eee.............
        .............eeeee............
        ............eee.e.e...........
        ............e.e.e..e..........
        ...........eee.eeee.e.........
        ...........e.e.e..ee..........
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        `)
    if (dryad.vy < 0) {
        dryad.setImage(img`
            ..............................
            ..............................
            ...............f..............
            ..............fef.............
            .............fecef............
            ............fecfcef...........
            ...........fecf5fcef..........
            ..........fecf525fcef.........
            ...........fecf5fcef..........
            ............fecfcef...........
            .............fecef............
            ..............fef.............
            ............eeeeeee...........
            ...........ee.eee.ee..........
            ...........ee.eee.ee..........
            ...........ee.eee.ee..........
            ...........ee.eee.ee..........
            ...........ee.eee.ee..........
            ..............eee.............
            ..............eee.............
            ..............eee.............
            .............eeee.............
            .............e.eee............
            .............e.e.e............
            .............e.e.e............
            ............e..e..e...........
            ............e...ee............
            .............e.e.e............
            ..............................
            ..............................
            `)
    }
    if (dryad.vy > 0) {
        dryad.setImage(img`
            ..............................
            ..............................
            ...............f..............
            ..............fef.............
            .............fecef............
            ............fecfcef...........
            ...........fecf5fcef..........
            ..........fecf525fcef.........
            ...........fecf5fcef..........
            ............fecfcef...........
            .............fecef............
            ..............fef.............
            ............eeeeeee...........
            ...........ee.eee.ee..........
            ...........ee.eee.ee..........
            .........e.ee.eee.ee..e.......
            .........e.ee.eee.ee.e........
            .........e.ee.eee.ee..e.......
            ..........e...eee....e........
            ...........eeeeeeeeeee........
            ..........e.e.eee.eee.........
            ...........e.eeeeee..e........
            ............eee.ee.ee.........
            ................e.............
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            `)
    }
    if (Math.abs(dryad.vx) > 0) {
        if (randint(0, 2) == 0) {
            dryad.setImage(img`
                ..............................
                ..............................
                ...............f..............
                ..............fef.............
                .............fecef............
                ............fecfcef...........
                ...........fecf5fcef..........
                ..........fecf525fcef.........
                ...........fecf5fcef..........
                ............fecfcef...........
                .............fecef............
                ..............fef.............
                ............eeeeeee...........
                ...........ee.eee.ee..........
                ...........ee.eee.ee..........
                ...........ee.eee.ee..........
                ...........ee.eee.ee..........
                ...........ee.eee.ee..........
                ..............eee.............
                .............eeeee............
                ............eee.e.e...........
                ............e.e.e..e..........
                ...........eee.eee..e.........
                ..........e..e.e.ee.e.........
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                `)
        } else if (randint(0, 2) == 1) {
            dryad.setImage(img`
                ..............................
                ..............................
                ...............f..............
                ..............fef.............
                .............fecef............
                ............fecfcef...........
                ...........fecf5fcef..........
                ..........fecf525fcef.........
                ...........fecf5fcef..........
                ............fecfcef...........
                .............fecef............
                ..............fef.............
                ............eeeeeee...........
                ...........ee.eee.ee..........
                ...........ee.eee.ee..........
                ...........ee.eee3ee..........
                ...........ee.eee.ee..........
                ...........ee.eee.ee..........
                ..............eee.............
                .............eeeee............
                ............eee.e.e...........
                ............ee..e..e..........
                ...........eeeee.ee.e.........
                ...........e.ee...ee..........
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                `)
        } else {
            dryad.setImage(img`
                ..............................
                ..............................
                ...............f..............
                ..............fef.............
                .............fecef............
                ............fecfcef...........
                ...........fecf5fcef..........
                ..........fecf525fcef.........
                ...........fecf5fcef..........
                ............fecfcef...........
                .............fecef............
                ..............fef.............
                ............eeeeeee...........
                ...........ee.eee.ee..........
                ...........ee.eee.ee..........
                ...........ee.eee.ee..........
                ...........ee.eee.ee..........
                ...........ee.eee.ee..........
                ..............eee.............
                .............eeeee............
                ............eee.e.e...........
                ............e.e.e.e...........
                ...........eee.e.ee...........
                ...........e.e..e.ee..........
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                `)
        }
    }
    if (dryad.vx < 0) {
        dryad.image.flipX()
    } else if (false) {
    	
    }
    if (g == -1) {
        dryad.image.flipY()
    }
    info.setScore(info.countdown() + coinseaten)
})
forever(function () {
    if (dryad.tileKindAt(TileDirection.Bottom, sprites.dungeon.floorLight0)) {
        controller.moveSprite(dryad, 400, 0)
    } else if (dryad.tileKindAt(TileDirection.Bottom, sprites.dungeon.floorLightMoss) || dryad.tileKindAt(TileDirection.Top, sprites.dungeon.floorLightMoss) || dryad.tileKindAt(TileDirection.Left, sprites.dungeon.floorLightMoss) || dryad.tileKindAt(TileDirection.Right, sprites.dungeon.floorLightMoss)) {
        die()
    } else if (dryad.tileKindAt(TileDirection.Bottom, sprites.dungeon.floorLight5)) {
        controller.moveSprite(dryad, 50, 0)
    } else if (dryad.tileKindAt(TileDirection.Bottom, sprites.builtin.forestTiles0)) {
        dryad.vy = -500
        pause(1000)
        dryad.vy = 0
    } else {
        controller.moveSprite(dryad, 100, 0)
    }
})
forever(function () {
    dryad.ay = 350 * g
})
